#ifndef AppConstants_H
#define AppConstants_H

enum
{
    MAIN_DIR =	0,
    SOUNDS_DIR,
    IMAGES_DIR,
    GENETICS_DIR,
    BODY_DATA_DIR,
	OVERLAYS_DIR,
    BACKGROUNDS_DIR,
    CATALOGUE_DIR,
	BOOTSTRAP_DIR,
	WORLDS_DIR,
	CREATURES_DIR,
	PRAYFILE_DIR,
	JOURNAL_DIR,
	CREATURE_DATABASE_DIR,
	NUM_DIRS
};

#endif//AppConstants_H