#ifndef AGENT_CONSTANTS_H
#define AGENT_CONSTANTS_H

#ifdef _MSC_VER
#pragma warning(disable:4786 4503)
#endif

#include "../Caos/AutoDocumentationTable.h"

extern TableSpec ourScriptNumbers[];
extern int sizeOurScriptNumbers;

// Standard event names.
enum 
{
	SCRIPTDEACTIVATE = 0,		
	SCRIPTACTIVATE1  = 1,
	SCRIPTACTIVATE2  = 2,
	SCRIPTHIT        = 3,
	SCRIPTPICKUP     = 4,	
	SCRIPTDROP       = 5,	
	SCRIPTCOLLISION  = 6,		 
	SCRIPTBUMP		 = 7,
	SCRIPTTIMER      = 9,	
    SCRIPTEAT        = 12,
	SCRIPTSTARTHOLDHANDS = 13,
	SCRIPTSTOPHOLDHANDS = 14,
	SCRIPTEXTRAQUIESCENT	= 16,	// stand and watch it
	SCRIPTEXTRAACT1			= 17,	// activate1 it
	SCRIPTEXTRAACT2			= 18,	// activate2 it
	SCRIPTEXTRADEAC			= 19,	// deactivate it
	SCRIPTEXTRASEEK			= 20,	// go up and look at it
	SCRIPTEXTRAAVOID		= 21,	// walk/run away from it
	SCRIPTEXTRAPICKUP		= 22,	// pick it up
	SCRIPTEXTRADROP			= 23,	// drop anything you're carrying
	SCRIPTEXTRANEED			= 24,	// say what's bothering you
	SCRIPTEXTRAREST			= 25,	// -- no such action needed; do not script ---
	SCRIPTEXTRAWEST			= 26,	// walk idly to west
	SCRIPTEXTRAEAST			= 27,	// walk idly to east
	SCRIPTEXTRAEAT      	= 28,	// eat it
	SCRIPTEXTRAHIT      	= 29,   // hit it
	SCRIPTEXTRAUNDEFINED3	= 30,
	SCRIPTEXTRAUNDEFINED4	= 31,
	// - introspective
	SCRIPTINTROQUIESCENT	= 32,	// stand and twiddle your thumbs
	SCRIPTINTROACT1			= 33,	// -- no such action needed; do not script ---
	SCRIPTINTROACT2			= 34,	// -- no such action needed; do not script ---
	SCRIPTINTRODEAC			= 35,	// -- no such action needed; do not script ---
	SCRIPTINTROSEEK			= 36,	// -- no such action needed; do not script ---
	SCRIPTINTROAVOID		= 37,	// -- no such action needed; do not script ---
	SCRIPTINTROPICKUP		= 38,	// -- no such action needed; do not script ---
	SCRIPTINTRODROP			= 39,	// drop anything you're carrying
	SCRIPTINTRONEED			= 40,	// say what's bothering you
	SCRIPTINTROREST			= 41,	// rest or sleep
	SCRIPTINTROWEST			= 42,	// walk idly to west
	SCRIPTINTROEAST			= 43,	// walk idly to east
	SCRIPTINTROEAT      	= 44,	// -- no such action needed; do not script ---
	SCRIPTINTROHIT      	= 45,   // -- no such action needed; do not script ---
	SCRIPTINTROUNDEFINED3	= 46,
	SCRIPTINTROUNDEFINED4	= 47,
	 
	// Creature scripts for Involuntary Actions, such as flinching and throwing a fit.
	// These are chemically invoked and produce reflexive or pathological behaviour
	SCRIPTINVOLUNTARY0		= 64,
	SCRIPTINVOLUNTARY1		= 65,
	SCRIPTINVOLUNTARY2		= 66,
	SCRIPTINVOLUNTARY3		= 67,
	SCRIPTINVOLUNTARY4		= 68,
	SCRIPTINVOLUNTARY5		= 69,
	SCRIPTINVOLUNTARY6		= 70,
	SCRIPTINVOLUNTARY7		= 71,
	SCRIPTDIE				= 72,
	SCRIPTRAWKEYDOWN		= 73,
	SCRIPTRAWKEYUP			= 74,
	SCRIPTRAWMOUSEMOVE		= 75,
	SCRIPTRAWMOUSEDOWN		= 76,
	SCRIPTRAWMOUSEUP		= 77,
	SCRIPTRAWMOUSEWHEEL		= 78,
	SCRIPTRAWTRANSLATEDCHAR = 79,
	// These are the 'cooked' script numbers generated by PointerAgent
	SCRIPTUIMIN				= 90,	//Range of UI nums (min)
	SCRIPTUIMOUSEDOWN		= 92,
	SCRIPTUIMAX				= 100,	//Range of UI nums (max)
	SCRIPTPOINTERACT1		= 101,	// left button click, causing activation1
	SCRIPTPOINTERACT2		= 102,	// left button click, causing activation2
	SCRIPTPOINTERDEAC		= 103,	// left button click, causing deactivation
	SCRIPTPOINTERPICKUP		= 104,	
	SCRIPTPOINTERDROP		= 105,	
	SCRIPTPOINTERPORTSELECT = 110,
	SCRIPTPOINTERPORTCONNECT = 111,
	SCRIPTPOINTERPORTDISCONNECT = 112,
	SCRIPTPOINTERPORTCANCEL = 113,
	SCRIPTPOINTERPORTERROR = 114,
	SCRIPTPOINTERHOLDHANDS = 115,
	SCRIPTPOINTERCLICKEDBACKGROUND = 116,
	SCRIPTPOINTERACTIONDISPATCH = 117,
	SCRIPTCONNECTIONBREAK = 118,

	SCRIPTSELECTEDCREATURECHANGED      = 120,
	SCRIPTPICKUPBYVEHICLE     = 121,
	SCRIPTDROPBYVEHICLE       = 122,
	SCRIPTWINDOWRESIZED		  = 123,
	SCRIPGOTCARRIEDAGENT        = 124, 
	SCRIPTLOSTCARRIEDAGENT		= 125,
	SCRIPT_MAKE_SPEECH_BUBBLE = 126,
	SCRIPT_LIFE_EVENT		  = 127,
	SCRIPT_WORLD_LOADED		  = 128,

    SCRIPTDONATESPERM         = 200,
	// Please change the documentation table in
	// AgentConstants.cpp if you add a new message,
	// or change the behaviour of one.  Tie a knot in 
	// your pyjamas.

	SCRIPTAGENTEXCEPTION      = 255,
	// Don't use numbers 256 or above
	// They are reserved for agent engineers to define how they want.
};

#endif //AGENT_CONSTANTS_H
